# Generated by Django 2.2.4 on 2019-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tokenlist_contractadress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenchange',
            name='T_type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tokenchange',
            name='buyer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokenchange',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
