# Generated by Django 2.2.4 on 2019-10-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190927_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='ABI',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='ContractAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='companyAccount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
