# Generated by Django 2.2.4 on 2019-10-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191004_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='MetamastAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
