# Generated by Django 2.2.4 on 2019-10-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client_info_metamastaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytoken',
            name='tokenname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TokenList'),
        ),
        migrations.AlterField(
            model_name='tokensell',
            name='tokenname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.TokenList'),
        ),
    ]
