# Generated by Django 2.2.4 on 2019-10-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191005_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlist',
            name='compname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company_info'),
        ),
    ]
