# Generated by Django 2.2.4 on 2019-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191005_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlist',
            name='compname',
            field=models.CharField(max_length=100),
        ),
    ]
