# Generated by Django 2.2.4 on 2019-10-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191005_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlist',
            name='compname',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Company_info'),
        ),
    ]
