# Generated by Django 2.2.4 on 2019-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191005_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buytoken',
            name='tokenname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tokensell',
            name='tokenname',
            field=models.CharField(max_length=100),
        ),
    ]
