# Generated by Django 2.2.4 on 2019-11-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191006_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensell',
            name='metamask_account',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
