# Generated by Django 2.2.4 on 2019-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_tokensell_metamask_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='KRW',
            field=models.FloatField(default=0),
        ),
    ]
