# Generated by Django 2.2.4 on 2019-11-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20191108_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestbuytoken',
            fields=[
                ('request_Code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('one_tokenprice', models.FloatField(default=0)),
                ('requesttoken_num', models.FloatField(default=0)),
                ('buyer_account', models.CharField(blank=True, max_length=200)),
                ('seller_account', models.CharField(blank=True, max_length=200)),
                ('sellertotaltoken', models.FloatField(default=0)),
                ('compnay_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company_info', unique=True)),
            ],
        ),
    ]
