# Generated by Django 2.2.4 on 2019-11-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_requestbuytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbuytoken',
            name='compnay_code',
            field=models.CharField(max_length=6),
        ),
    ]
