# Generated by Django 2.2.4 on 2019-11-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20191112_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestbuytoken',
            fields=[
                ('request_Code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('compnay_code', models.CharField(max_length=6)),
                ('one_tokenprice', models.FloatField(default=0)),
                ('requesttoken_num', models.FloatField(default=0)),
                ('buyer_account', models.CharField(blank=True, max_length=200)),
                ('seller_account', models.CharField(blank=True, max_length=200)),
                ('sellertotaltoken', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
