# Generated by Django 2.2.5 on 2019-11-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20191115_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoken',
            name='requestcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
