# Generated by Django 2.2.5 on 2019-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_requesttoken_requestcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenchange',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='Cli_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client_account',
            name='Company_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='token',
            name='tokenname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenchange',
            name='tokenname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenlist',
            name='compname',
            field=models.CharField(max_length=100),
        ),
    ]
