# Generated by Django 2.2.5 on 2019-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_company_info_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenname', models.CharField(max_length=100)),
                ('initial', models.CharField(max_length=100)),
                ('quota', models.FloatField(default=0)),
                ('metamaskaddress', models.CharField(max_length=200)),
            ],
        ),
    ]
