# Generated by Django 2.2.5 on 2019-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_tokenorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokenwhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
                ('Client_code', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='requesttoken',
            name='date',
        ),
    ]
