# Generated by Django 2.2.5 on 2019-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20191123_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='person',
            field=models.CharField(max_length=100),
        ),
    ]
