# Generated by Django 2.2.4 on 2019-11-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20191123_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='keyinfo',
            field=models.ImageField(default='image/defaultinfo.jpg', upload_to='image'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='photo',
            field=models.ImageField(default='image/default.jpg', upload_to='image'),
        ),
    ]
