# Generated by Django 2.2.4 on 2019-11-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20191124_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoken',
            name='whlist_check',
            field=models.IntegerField(default=0),
        ),
    ]
