# Generated by Django 2.2.4 on 2019-11-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_requesttoken_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensell',
            name='standby',
            field=models.IntegerField(default=0),
        ),
    ]
