# Generated by Django 2.2.4 on 2019-11-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_tokensell_standby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensell',
            name='standby',
            field=models.FloatField(default=0),
        ),
    ]
