# Generated by Django 2.2.4 on 2019-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20191124_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensell',
            name='sell_code',
            field=models.IntegerField(default=0),
        ),
    ]
