# Generated by Django 2.2.4 on 2019-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_codecounting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecounting',
            name='id',
        ),
        migrations.AddField(
            model_name='codecounting',
            name='primarykey',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
