# Generated by Django 2.2.4 on 2019-11-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20191124_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttoken',
            name='sell_code',
            field=models.IntegerField(default=0),
        ),
    ]
