# Generated by Django 2.2.4 on 2019-11-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_requesttoken_sell_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenchange',
            name='sell_code',
            field=models.IntegerField(default=0),
        ),
    ]
