# Generated by Django 2.2.4 on 2019-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_tokenchange_sell_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenchange',
            name='request_code',
            field=models.IntegerField(default=0),
        ),
    ]
