# Generated by Django 2.2.5 on 2019-11-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_tokenchange_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorder',
            name='divide',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='state',
            field=models.CharField(choices=[('0', '토큰 예약 대기'), ('1', '토큰 생성 완료'), ('2', 'ABI대기'), ('3', '화아트 리스트 등록 대기')], max_length=1, null=True),
        ),
    ]
