# Generated by Django 2.2.5 on 2019-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20191124_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenlist',
            name='wlistABI',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='tokenlist',
            name='wlistAddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
