# Generated by Django 2.2.5 on 2019-11-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_auto_20191125_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenorder',
            name='state',
            field=models.CharField(choices=[('0', '토큰 예약 대기'), ('1', '토큰 생성 완료'), ('2', 'ABI대기'), ('3', '화이트 리스트 등록'), ('4', '토큰 최종 발행'), ('5', '거래 중')], max_length=1, null=True),
        ),
    ]
