# Generated by Django 2.2.5 on 2019-11-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20191125_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenlist',
            name='ABI',
        ),
        migrations.RemoveField(
            model_name='tokenlist',
            name='wlistABI',
        ),
    ]
