# Generated by Django 2.2.4 on 2019-11-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_auto_20191126_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='input_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client_info',
            name='input_bank',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='client_info',
            name='output_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client_info',
            name='output_bank',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
