# Generated by Django 2.2.4 on 2019-11-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_auto_20191126_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='bankstatus',
            field=models.IntegerField(default=0),
        ),
    ]
