# Generated by Django 2.2.4 on 2019-09-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyCode', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=24)),
            ],
        ),
    ]
