# Generated by Django 2.2.4 on 2019-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='PresidentEmail',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
