# Generated by Django 2.2.4 on 2019-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_company_presidentemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='PresidentEmail',
            field=models.CharField(max_length=24),
        ),
    ]
